export const bookmarksMock: chrome.bookmarks.BookmarkTreeNode[] = [
  {
    id: '1',
    title: 'Bookmarks Bar',
    children: [
      {
        dateAdded: 1640003272925,
        dateGroupModified: 1650557228175,
        id: '21',
        index: 0,
        parentId: '1',
        title: 'mail',
        children: [
          {
            dateAdded: 1640003305323,
            id: '22',
            index: 0,
            parentId: '21',
            title: 'personal',
            url: 'https://mail.google.com/mail/u/0/',
          },
          {
            dateAdded: 1640003319074,
            id: '23',
            index: 1,
            parentId: '21',
            title: 'work',
            url: 'https://mail.google.com/mail/u/1/',
          },
          {
            dateAdded: 1640003272925,
            dateGroupModified: 1650557228175,
            id: '8889',
            index: 2,
            parentId: '21',
            title: 'other',
            children: [
              {
                dateAdded: 1640003305323,
                id: '8886',
                index: 0,
                parentId: '8889',
                title: 'other',
                url: 'https://mail.google.com/mail/u/0/',
              },
            ],
          },
        ],
      },
      {
        dateAdded: 1646899075825,
        id: '53',
        index: 1,
        parentId: '1',
        title: 'asana',
        url: 'https://app.asana.com/',
      },
      {
        dateAdded: 1655905306394,
        id: '72',
        index: 2,
        parentId: '1',
        title: 'gitlab',
        url: 'https://gitlab.com/',
      },
      {
        dateAdded: 1640003728349,
        id: '26',
        index: 3,
        parentId: '1',
        title: 'figma',
        url: 'https://figma.com/',
      },
      {
        dateAdded: 1640030404050,
        id: '29',
        index: 4,
        parentId: '1',
        title: 'youtube',
        url: 'https://youtube.com/',
      },
      {
        dateAdded: 1640003698186,
        id: '25',
        index: 5,
        parentId: '1',
        title: 'google sheets',
        url: 'https://docs.google.com/spreadsheets/',
      },
      {
        dateAdded: 1644314342791,
        id: '43',
        index: 6,
        parentId: '1',
        title: 'google drive',
        url: 'https://drive.google.com/drive/u/0/my-drive',
      },
      {
        dateAdded: 1647255229052,
        id: '57',
        index: 7,
        parentId: '1',
        title: 'wise',
        url: 'https://wise.com/',
      },
      {
        dateAdded: 1649328858112,
        id: '60',
        index: 8,
        parentId: '1',
        title: 'notion',
        url: 'https://notion.so/',
      },
      {
        dateAdded: 1653044276218,
        id: '65',
        index: 9,
        parentId: '1',
        title: 'linkedin',
        url: 'https://linkedin.com/',
      },
      {
        dateAdded: 1655818871618,
        id: '67',
        index: 10,
        parentId: '1',
        title: 'app icon generator',
        url: 'https://icon.kitchen/',
      },
      {
        dateAdded: 1655850071949,
        id: '70',
        index: 11,
        parentId: '1',
        title: 'github',
        url: 'https://github.com/',
      },
      {
        dateAdded: 1646227295394,
        id: '51',
        index: 12,
        parentId: '1',
        title: 'google maps',
        url: 'https://www.google.com/maps',
      },
      {
        dateAdded: 1656242775047,
        id: '81',
        index: 1,
        parentId: '1',
        title: 'airbnb',
        url: 'https://www.airbnb.com/',
      },
    ],
  },
];
